apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogocursos-mysql-deployment
spec:
  selector:
    matchLabels:
      app: catalogocursos-mysql-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: catalogocursos-mysql-service
    spec:
      containers:
        - image: mysql:5.7.23
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: cursos_autentia
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: catalogocursos-mysql-pv-claim
